package com.aurospaces.neighbourhood.bean;


import java.util.Date;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


/**
 *
 * @author autogenerated
 */



public class BranchProducts 
{

		 /** Field mapping. **/
protected int id   = 0;

/** Field mapping. **/
protected Date createdTime ;

/** Field mapping. **/
protected Date updatedTime ;

/** Field mapping. **/
protected String branchId ;

/** Field mapping. **/
protected String productId ;

public int getId() {
	return id;
}

public void setId(int id) {
	this.id = id;
}

public Date getCreatedTime() {
	return createdTime;
}

public void setCreatedTime(Date createdTime) {
	this.createdTime = createdTime;
}

public Date getUpdatedTime() {
	return updatedTime;
}

public void setUpdatedTime(Date updatedTime) {
	this.updatedTime = updatedTime;
}

public String getBranchId() {
	return branchId;
}

public void setBranchId(String branchId) {
	this.branchId = branchId;
}

public String getProductId() {
	return productId;
}

public void setProductId(String productId) {
	this.productId = productId;
}


}