package com.aurospaces.neighbourhood.bean;


import java.util.Date;


/**
 *
 * @author autogenerated
 */



public class CartBean 
{
protected int id   = 0;

/** Field mapping. **/
protected Date createdTime ;

/** Field mapping. **/
protected Date updatedTime ;

/** Field mapping. **/
protected String productId ;

/** Field mapping. **/
protected String quantity,amount,totalamount ;




public String getTotalamount() {
	return totalamount;
}
public void setTotalamount(String totalamount) {
	this.totalamount = totalamount;
}
public String getAmount() {
	return amount;
}
public void setAmount(String amount) {
	this.amount = amount;
}
/** Field mapping. **/
protected String userId ;

/** Field mapping. **/
protected String branchId,cartList ;


public String getCartList() {
	return cartList;
}
public void setCartList(String cartList) {
	this.cartList = cartList;
}
public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}
public Date getCreatedTime()
{
  return createdTime;
}
public void setCreatedTime(final Date createdTime)
{
  this.createdTime = createdTime;
}
public Date getUpdatedTime()
{
  return updatedTime;
}
public void setUpdatedTime(final Date updatedTime)
{
  this.updatedTime = updatedTime;
}
public String getProductId()
{
  return productId;
}
public void setProductId(final String productId)
{
  this.productId = productId;
}
public String getQuantity()
{
  return quantity;
}
public void setQuantity(final String quantity)
{
  this.quantity = quantity;
}
public String getUserId()
{
  return userId;
}
public void setUserId(final String userId)
{
  this.userId = userId;
}
public String getBranchId()
{
  return branchId;
}
public void setBranchId(final String branchId)
{
  this.branchId = branchId;
}

}