package com.aurospaces.neighbourhood.bean;


import java.util.Date;


/**
 *
 * @author autogenerated
 */



public class EmployeeBean 
{

protected int id   = 0;

/** Field mapping. **/
protected Date createdTime ;

/** Field mapping. **/
protected Date updatedTime ;

/** Field mapping. **/
protected String name ;

/** Field mapping. **/
protected String shopname ;

/** Field mapping. **/
protected String address ;

/** Field mapping. **/
protected String city ;

/** Field mapping. **/
protected String pincode ;

/** Field mapping. **/
protected String shopPhone ;

/** Field mapping. **/
protected String gstno ;

/** Field mapping. **/
protected String phoneNumber ;

/** Field mapping. **/
protected String email ;

/** Field mapping. **/
protected String description ;

/** Field mapping. **/
protected String branchId ;

/** Field mapping. **/
protected String roleId ;

/** Field mapping. **/
protected String password ;

/** Field mapping. **/
protected String username ;

/** Field mapping. **/
protected String status ;
protected String branchname;
protected String bName;
protected String roleName;
protected String empCreationStatus;




public String getbName() {
	return bName;
}
public void setbName(String bName) {
	this.bName = bName;
}
public String getRoleName() {
	return roleName;
}
public void setRoleName(String roleName) {
	this.roleName = roleName;
}
public String getEmpCreationStatus() {
	return empCreationStatus;
}
public void setEmpCreationStatus(String empCreationStatus) {
	this.empCreationStatus = empCreationStatus;
}
public String getBranchname() {
	return branchname;
}
public void setBranchname(String branchname) {
	this.branchname = branchname;
}
public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}
public Date getCreatedTime()
{
  return createdTime;
}
public void setCreatedTime(final Date createdTime)
{
  this.createdTime = createdTime;
}
public Date getUpdatedTime()
{
  return updatedTime;
}
public void setUpdatedTime(final Date updatedTime)
{
  this.updatedTime = updatedTime;
}
public String getName()
{
  return name;
}
public void setName(final String name)
{
  this.name = name;
}
public String getShopname()
{
  return shopname;
}
public void setShopname(final String shopname)
{
  this.shopname = shopname;
}
public String getAddress()
{
  return address;
}
public void setAddress(final String address)
{
  this.address = address;
}
public String getCity()
{
  return city;
}
public void setCity(final String city)
{
  this.city = city;
}
public String getPincode()
{
  return pincode;
}
public void setPincode(final String pincode)
{
  this.pincode = pincode;
}
public String getShopPhone()
{
  return shopPhone;
}
public void setShopPhone(final String shopPhone)
{
  this.shopPhone = shopPhone;
}
public String getGstno()
{
  return gstno;
}
public void setGstno(final String gstno)
{
  this.gstno = gstno;
}
public String getPhoneNumber()
{
  return phoneNumber;
}
public void setPhoneNumber(final String phoneNumber)
{
  this.phoneNumber = phoneNumber;
}
public String getEmail()
{
  return email;
}
public void setEmail(final String email)
{
  this.email = email;
}
public String getDescription()
{
  return description;
}
public void setDescription(final String description)
{
  this.description = description;
}
public String getBranchId()
{
  return branchId;
}
public void setBranchId(final String branchId)
{
  this.branchId = branchId;
}
public String getRoleId()
{
  return roleId;
}
public void setRoleId(final String roleId)
{
  this.roleId = roleId;
}
public String getPassword()
{
  return password;
}
public void setPassword(final String password)
{
  this.password = password;
}
public String getUsername()
{
  return username;
}
public void setUsername(final String username)
{
  this.username = username;
}
public String getStatus()
{
  return status;
}
public void setStatus(final String status)
{
  this.status = status;
}

}