package com.aurospaces.neighbourhood.bean;


import java.util.Date;


/**
 *
 * @author autogenerated
 */



public class OrdersListBean 
{

protected int id   = 0;
protected Date createdTime ;
protected Date updatedTime ;
protected String delerId ;
protected String quantity ;
protected String productId,invoiceId,orderId,branchId,balanceqty ;


public String getBalanceqty() {
	return balanceqty;
}
public void setBalanceqty(String balanceqty) {
	this.balanceqty = balanceqty;
}
public String getBranchId() {
	return branchId;
}
public void setBranchId(String branchId) {
	this.branchId = branchId;
}
public String getOrderId() {
	return orderId;
}
public void setOrderId(String orderId) {
	this.orderId = orderId;
}
public String getInvoiceId() {
	return invoiceId;
}
public void setInvoiceId(String invoiceId) {
	this.invoiceId = invoiceId;
}
public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}
public Date getCreatedTime()
{
  return createdTime;
}
public void setCreatedTime(final Date createdTime)
{
  this.createdTime = createdTime;
}
public Date getUpdatedTime()
{
  return updatedTime;
}
public void setUpdatedTime(final Date updatedTime)
{
  this.updatedTime = updatedTime;
}
public String getDelerId()
{
  return delerId;
}
public void setDelerId(final String delerId)
{
  this.delerId = delerId;
}
public String getQuantity()
{
  return quantity;
}
public void setQuantity(final String quantity)
{
  this.quantity = quantity;
}
public String getProductId()
{
  return productId;
}
public void setProductId(final String productId)
{
  this.productId = productId;
}

}