package com.aurospaces.neighbourhood.bean;


import java.util.Date;


/**
 *
 * @author autogenerated
 */



public class PaymentBean 
{

protected int id   = 0;
protected Date createdTime ;
protected Date updatedTime ;
protected String empId ;
protected String branchId ;
protected String amount ;
protected String confirm ;
protected Date paymentDate ;
protected String strpaymentDate ;
protected String qtrNumber ;
protected String comment ;

public String getComment() {
	return comment;
}
public void setComment(String comment) {
	this.comment = comment;
}
public String getStrpaymentDate() {
	return strpaymentDate;
}
public void setStrpaymentDate(String strpaymentDate) {
	this.strpaymentDate = strpaymentDate;
}
public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}
public Date getCreatedTime()
{
  return createdTime;
}
public void setCreatedTime(final Date createdTime)
{
  this.createdTime = createdTime;
}
public Date getUpdatedTime()
{
  return updatedTime;
}
public void setUpdatedTime(final Date updatedTime)
{
  this.updatedTime = updatedTime;
}
public String getEmpId()
{
  return empId;
}
public void setEmpId(final String empId)
{
  this.empId = empId;
}
public String getBranchId()
{
  return branchId;
}
public void setBranchId(final String branchId)
{
  this.branchId = branchId;
}
public String getAmount()
{
  return amount;
}
public void setAmount(final String amount)
{
  this.amount = amount;
}
public String getConfirm()
{
  return confirm;
}
public void setConfirm(final String confirm)
{
  this.confirm = confirm;
}
public Date getPaymentDate()
{
  return paymentDate;
}
public void setPaymentDate(final Date paymentDate)
{
  this.paymentDate = paymentDate;
}
public String getQtrNumber()
{
  return qtrNumber;
}
public void setQtrNumber(final String qtrNumber)
{
  this.qtrNumber = qtrNumber;
}

}